# WHeroesAddon config by Wiedzmin137

# Configs for SkillTrees
SkillTree:
  #Are the SkillTree enabled [WARNING: Need tests!]?
  Enabled: true

  #Sets how many SkillPoints the player will earn/lose per level.  
  Points_Per_Level: 1

  #Sets the cost to unlock a skill (PLANNED)
  #Cost_Unlock: 0

  #Sets the cost to level up a skill (PLANNED)
  #Cost_Level_Up: 0

  #Sets the cost to level down a skill (PLANNED)
  #Cost_Level_Down: 0

  #Sets the cost to reset all stats (PLANNED)
  #Cost_Reset: 0

MySQL:
  enabled: false
  host: 127.0.0.1
  port: 3306
  user: root
  password: INSERT PASSWORD
  database: WHeroesAddon