# WHeroesAddon config by Wiedzmin137

# Configs for SkillTree
SkillTree:
  #Should SkillTree be enabled?
  Enabled: true

  #Should skills be locked it not unlocked?
  SkillsDefaultLocked: false

  #Sets how many SkillPoints the player will earn/lose per level.  
  Points_Per_Level: 1

  #Sets is skill downgrading be enabled (PLANNED)
  #SkillDowngrading: false

  #Sets the cost to unlock a skill (PLANNED)
  #Cost_Unlock: 0

  #Sets the cost to level up a skill (PLANNED)
  #Cost_Level_Up: 0

  #Sets the cost to level down a skill (PLANNED)
  #Cost_Level_Down: 0

  #Sets the cost to reset all stats (PLANNED)
  #Cost_Reset: 0

# Configs for CooldownScoreboard
CooldownScoreboard:
  #Should CooldownScoreboard be enabled?
  Enabled: true

# Configs for SkillBar
SkillBar:
  #Should SkillBar be enabled?
  Enabled: true

  Items:
    #Default item for SkillItem
    Skill: GOLD_RECORD
    #Default item for BlockItem
    Block: RECORD_11

MySQL:
  Enabled: false
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password: INSERT PASSWORD
  Database: WHeroesAddon