name: WHeroesAddon
main: me.wiedzmin137.wheroesaddon.WHeroesAddon
version: A0.2
authors: [Wiedzmin137, Bednar12]
softdepend: [Heroes, ScrollingMenuSign]

website: https://github.com/RPGDevTeam/WHeroesAddon-Rewrited
description: Brings skill trees to the Heroes plugin.

commands:
    skilltree:
        aliases: [st]
        description: Turn on your SkillTree
        usage: "/<command>"