name: WHeroesAddon
main: me.wiedzmin137.wheroesaddon.WHeroesAddon
version: A0.1
authors: [Wiedzmin137, Bednar12]
softdepend: [Heroes, ScrollingMenuSign]

website: https://github.com/RPGDevTeam/WHeroesAddon-Rewrited
description: Brings skill trees to the Heroes plugin.

commands:
    skilltree:
        aliases: [st]
        description: Turn on your SkillTree
        usage: "/<command>"

permissions:
  skilltree.*:
    description: Gives all permissions
    default: op
    children:
      skilltree.up: true
      skilltree.down: true
      skilltree.lock: true
      skilltree.info: true
  skilltree.override.*:
    description: Gives player total override powers over skill limitations
    children:
      stilltree.override.locked: true
      skilltree.override.unlock: true
      skilltree.override.usepoints: true
  skilltree.override.locked:
    description: Allows player to use locked skills
  skilltree.override.unlock:
    description: Allows players to unlock skills freely ignoring parentship
  skilltree.override.usepoints:
    description: Player's points don't increase/decrease when leveling up/down skills
  skilltree.up:
    description: Allows leveling up skills
    default: true
  skilltree.down:
    description: Allows leveling down skills
  skilltree.lock:
    description: Allows player to re-lock a skill
  skilltree.info:
    description: Allows player to check a skill's info
    default: true
  skilltree.points:
    description: Allows player to check his SkillPoints
    default: true
  skilltree.skillgui:
    description: Allows player to use his SkillTree GUI
    default: true